services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:8000
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: naturalva123
      MYSQL_DATABASE: publisher_siciva
      MYSQL_USER: root
      MYSQL_PASSWORD: naturalva123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  supervisor:
    image: supervisor:latest
    container_name: laravel_supervisor
    restart: unless-stopped
    volumes:
      - ./supervisor:/etc/supervisor/conf.d
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
