services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:8000
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  supervisor:
    image: ubuntu:latest
    container_name: laravel_supervisor
    command: /bin/bash -c "apt-get update && apt-get install -y supervisor && supervisord -c /etc/supervisor/supervisord.conf"
    restart: unless-stopped
    volumes:
      - ./supervisor:/etc/supervisor
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
